version: "3"
services:
  proxy:
    image: ghcr.io/bacpop/beebop-proxy:${GIT_SHA}
    depends_on:
      - beebop-server
    ports:
      - 80:80
      - 443:443
    command:
      $HOST beebop-server
  beebop-server:
    image: ghcr.io/bacpop/beebop-server:${GIT_SHA}
    depends_on:
      - beebop-py-api
      - beebop-redis
  beebop-py-api:
    image: ghcr.io/bacpop/beebop-py:${API_IMAGE}
    depends_on:
      - beebop-redis
    volumes:
      - beebop-storage:/beebop/storage
    environment:
      - REDIS_HOST=beebop-redis
      - STORAGE_LOCATION=./storage
  beebop-redis:
    image: redis:5.0
  beebop-py-worker:
    image: ghcr.io/bacpop/beebop-py:${API_IMAGE}
    depends_on:
      - beebop-redis
    command:
      rqworker
    volumes:
      - beebop-storage:/beebop/storage
    environment:
      - REDIS_HOST=beebop-redis
volumes:
  beebop-storage:
