/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AmrColumn: typeof import('./src/components/ProjectView/AmrColumn.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    CytoscapeCanvas: typeof import('./src/components/ProjectView/CytoscapeCanvas.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    ExternalLink: typeof import('./src/components/Common/ExternalLink.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    Image: typeof import('primevue/image')['default']
    InlineMessage: typeof import('primevue/inlinemessage')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MicroReactColumn: typeof import('./src/components/ProjectView/MicroReactColumn.vue')['default']
    MicroReactTokenDialog: typeof import('./src/components/ProjectView/MicroReactTokenDialog.vue')['default']
    NetworkGraph: typeof import('./src/components/ProjectView/NetworkGraph.vue')['default']
    NetworkTab: typeof import('./src/components/ProjectView/NetworkTab.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    ProjectDataTable: typeof import('./src/components/ProjectView/ProjectDataTable.vue')['default']
    ProjectPage: typeof import('./src/components/ProjectView/ProjectPage.vue')['default']
    ProjectPostRun: typeof import('./src/components/ProjectView/ProjectPostRun.vue')['default']
    ProjectPreRun: typeof import('./src/components/ProjectView/ProjectPreRun.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('primevue/sidebar')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    Tag: typeof import('primevue/tag')['default']
  }
}
