steps:
  - label: ":whale::vue: Build Server"
    command: app/server/docker/build

  - label: ":whale::vue: Build Client"
    command: app/client/docker/build

  - label: ":whale::nginx: Build Proxy"
    command: proxy/docker/build

  - wait

  - label: ":shipit: Push Server images"
    command: app/server/docker/push

  - label: ":shipit: Push Proxy images"
    command:  proxy/docker/push
