#!/usr/bin/env bash
set -e

REGISTRY=ghcr.io
PACKAGE_ROOT=$(realpath $HERE/..)
PACKAGE_NAME=beebop-proxy
PACKAGE_ORG=mrcide

GIT_SHA=$(git -C "$PACKAGE_ROOT" rev-parse --short=7 HEAD)
if [[ -v "BRANCH_NAME" ]]; then
    GIT_BRANCH=${BRANCH_NAME}
else
    GIT_BRANCH=$(git symbolic-ref --short HEAD)
fi


TAG_SHA="${REGISTRY}/${PACKAGE_ORG}/${PACKAGE_NAME}:${GIT_SHA}"
TAG_BRANCH="${REGISTRY}/${PACKAGE_ORG}/${PACKAGE_NAME}:${GIT_BRANCH}"
TAG_LATEST="${REGISTRY}/${PACKAGE_ORG}/${PACKAGE_NAME}:latest"
