#!/usr/bin/env bash
export API_IMAGE="metadata-map-pneumo-view" # TODO: revert to main before merge

NETWORK=beebop_nw
VOLUME=beebop-storage
NAME_REDIS=beebop-redis
NAME_API=beebop-py-api
NAME_WORKER=beebop-py-worker
PORT=5000
