#!/usr/bin/env bash
export API_IMAGE="bacpop-209-amr-microreact-dev" # TODO revert back to main before merge into main

NETWORK=beebop_nw
VOLUME=beebop-storage
NAME_REDIS=beebop-redis
NAME_API=beebop-py-api
NAME_WORKER=beebop-py-worker
PORT=5000
