#!/usr/bin/env bash
export API_IMAGE="bacpop-71-sublineage-dev" # TODO revert before merge

NETWORK=beebop_nw
VOLUME=beebop-storage
NAME_REDIS=beebop-redis
NAME_API=beebop-py-api
NAME_WORKER=beebop-py-worker
PORT=5000
