#!/usr/bin/env bash
set -ex

HERE=$(realpath "$(dirname $0)")
. $HERE/common

DEFAULT_MOUNT=$VOLUME

if [ -z "$1" ]; then
    echo "No mount path provided, using default: $DEFAULT_MOUNT"
    BIND_MOUNT=$DEFAULT_MOUNT
else
    BIND_MOUNT=$1
fi

docker run --rm -v $VOLUME:/beebop/storage \
       -v $BIND_MOUNT:/beebop/storage/dbs \
       --pull always \
       ghcr.io/bacpop/beebop-py:$API_IMAGE \
       ./scripts/download_databases --refs # remove --refs to download all databases