#!/usr/bin/env bash
set -ex

HERE=$(realpath "$(dirname $0)")
. $HERE/common

NETWORK=beebop_nw
VOLUME=beebop-storage
NAME_REDIS=beebop-redis
NAME_API=beebop-py-api
NAME_WORKER=beebop-py-worker
PORT=5000

docker volume create $VOLUME
docker run --rm -v $VOLUME:/beebop/storage mrcide/beebop-py:$API_BRANCH \
       ./scripts/download_db
docker network create $NETWORK > /dev/null || /bin/true

docker run -d --rm --name $NAME_REDIS --network=$NETWORK -p 6379:6379 redis:5.0
docker run -d --rm --name $NAME_WORKER --network=$NETWORK \
       --env=REDIS_HOST="$NAME_REDIS" \
       --pull always \
       -v $VOLUME:/beebop/storage \
       mrcide/beebop-py:$API_BRANCH rqworker
docker run -d --rm --name $NAME_API --network=$NETWORK \
       --env=REDIS_HOST="$NAME_REDIS" \
       --env=STORAGE_LOCATION="./storage" \
       --env=DB_LOCATION="$DB_LOCATION" \
       -v $VOLUME:/beebop/storage \
       -p $PORT:5000 \
       mrcide/beebop-py:$API_BRANCH