#!/usr/bin/env bash
set -ex

HERE=$(realpath "$(dirname $0)")
. $HERE/common


. $HERE/parse_mount_arg
MOUNT=$(parse_mount_arg "$@")

if [ -z "$MOUNT" ]; then
       echo "No mount path provided, using default: $VOLUME"
       MOUNT=$VOLUME
       docker volume create $VOLUME
fi

docker network create $NETWORK > /dev/null || /bin/true

docker run --rm -v $MOUNT:/beebop/storage \
       --pull always \
       ghcr.io/bacpop/beebop-py:$API_IMAGE \
       ./scripts/download_databases

docker run -d --rm --name $NAME_REDIS --network=$NETWORK -p 6379:6379 redis:5.0
docker run -d --rm --name $NAME_WORKER --network=$NETWORK \
       --pull always \
       --env=REDIS_HOST="$NAME_REDIS" \
       -v $MOUNT:/beebop/storage \
       ghcr.io/bacpop/beebop-py:$API_IMAGE rqworker

docker run -d --rm --name $NAME_API --network=$NETWORK \
       --pull always \
       --env=REDIS_HOST="$NAME_REDIS" \
       --env=STORAGE_LOCATION="./storage" \
       --env=DBS_LOCATION="./storage/dbs" \
       -v $MOUNT:/beebop/storage \
       -p $PORT:5000 \
       ghcr.io/bacpop/beebop-py:$API_IMAGE