#!/usr/bin/env bash
set -ex

HERE=$(realpath "$(dirname $0)")
. $HERE/common

docker volume create $VOLUME

if [ -z "$1" ]; then
    echo "No mount path provided, using default: $VOLUME"
    BIND_MOUNT=$VOLUME
else
    BIND_MOUNT=$1
fi
docker network create $NETWORK > /dev/null || /bin/true

docker run --rm -v $BIND_MOUNT:/beebop/storage \
       --pull always \
       ghcr.io/bacpop/beebop-py:$API_IMAGE \
       ./scripts/download_databases --refs # remove --refs to download all databases

docker run -d --rm --name $NAME_REDIS --network=$NETWORK -p 6379:6379 redis:5.0
docker run -d --rm --name $NAME_WORKER --network=$NETWORK \
       --pull always \
       --env=REDIS_HOST="$NAME_REDIS" \
       -v $BIND_MOUNT:/beebop/storage \
       ghcr.io/bacpop/beebop-py:$API_IMAGE rqworker

docker run -d --rm --name $NAME_API --network=$NETWORK \
       --pull always \
       --env=REDIS_HOST="$NAME_REDIS" \
       --env=STORAGE_LOCATION="./storage" \
       --env=DBS_LOCATION="./storage/dbs" \
       -v $BIND_MOUNT:/beebop/storage \
       -p $PORT:5000 \
       ghcr.io/bacpop/beebop-py:$API_IMAGE