#!/usr/bin/env bash
set -ex

HERE=$(realpath "$(dirname $0)")
. $HERE/common

if [ "$1" == "decrypt" ]; then
  export VAULT_ADDR=https://vault.dide.ic.ac.uk:8200
  vault login -method=github
  . $HERE/decrypt_config docker
fi

export GIT_SHA=$(git -C . rev-parse --short=7 HEAD)

export HOST="localhost"

docker-compose up -d
docker cp app/server/src/resources/config.json beebop_beebop-server_1:/app/src/resources/config.json
docker cp proxy/ssl/dhparam.pem beebop_proxy_1:/run/proxy/
docker cp proxy/$SSL_PATH/certificate.pem beebop_proxy_1:/run/proxy/
docker cp proxy/$SSL_PATH/key.pem beebop_proxy_1:/run/proxy/
docker run --rm -v beebop_beebop-storage:/beebop/storage mrcide/beebop-py:${API_BRANCH} \
       ./scripts/download_db --small storage
