#!/usr/bin/env bash
set -ex

HERE=$(realpath "$(dirname $0)")
. $HERE/common

if [ "$#" -eq 1 ]; then
  HOST=$1
  SSL_PATH=ssl/production
else
  HOST="localhost"
  SSL_PATH=ssl
fi
export HOST

export GIT_SHA=$(git -C . rev-parse --short=7 HEAD)

docker compose up -d --pull always
docker cp app/server/src/resources/config.json beebop-beebop-server-1:/app/src/resources/config.json
docker cp proxy/ssl/dhparam.pem beebop-proxy-1:/run/proxy/
docker cp proxy/$SSL_PATH/certificate.pem beebop-proxy-1:/run/proxy/
docker cp proxy/$SSL_PATH/key.pem beebop-proxy-1:/run/proxy/
docker run --rm -v beebop_beebop-storage:/beebop/storage mrcide/beebop-py:main \
       ./scripts/download_db 
