name: jest CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_frontend:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/client
        
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./app/client/package-lock.json
    - run: npm ci
    - name: Run unit tests
      run: npm run test:unit
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
    
  unit_and_integration_backend:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/server
        
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./app/client/package-lock.json
    - run: npm ci
    - name: get config file
      run: |
        pwd
        cp ./src/resources/config.json.in.development ./src/resources/config.json
    - name: Run all components
      working-directory: .
      run: ./scripts/run_test
    - name: Run unit and integration tests
      run: npm run test
    - name: Stop all components
      working-directory: .
      run: ./scripts/stop_test
