name: jest CI

on:
  push:
    branches:
      - main
      - 'bacpop-*'
  pull_request:
    branches:
      - main
      - 'bacpop-*'
      

jobs:
  unit_frontend:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/client-v2
        
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./app/client-v2/package-lock.json
    - run: npm ci
    - name: Run unit tests
      run: npm run test:unit
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
    
  unit_and_integration_backend:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/server
        
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./app/server/package-lock.json
    - run: npm ci
    - name: get config file
      run: |
        pwd
        cp ./src/resources/config.json.in.development ./src/resources/config.json
    - name: run all components 
      working-directory: .
      run: ./scripts/run_test server-only
    - name: Run unit and integration tests
      run: npm run test
    - name: stop all components
      working-directory: .
      run: ./scripts/stop_test server-only
