name: jest CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_frontend:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/client
        
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./app/client/package-lock.json
    - run: npm ci
    - name: Run unit tests
      run: npm run test:unit
    
  unit_and_integration_backend:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/server
        
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./app/client/package-lock.json
    - run: npm ci
    - name: get config file
      run: cp ./app/server/src/resources/config.json.enc ./app/server/src/resources/config.json
    - name: Run unit tests
      run: npm run test
