name: playwright CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - "bacpop-*"

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./app/client-v2/package-lock.json
      - name: get config file
        run: |
          pwd
          cp ./app/server/src/resources/config.json.in.development ./app/server/src/resources/config.json
      - name: Run all components
        working-directory: .
        run: ./scripts/run_test
      - name: Install playwright
        working-directory: ./app/client-v2
        run: npx playwright install --with-deps
      - name: Run e2e tests
        env:
          MICROREACT_TOKEN: ${{ secrets.MICROREACT_TOKEN }}
        working-directory: ./app/client-v2
        run: npm run test:e2e:${{ matrix.browser}}
      - name: Stop all components
        if: always()
        working-directory: .
        run: ./scripts/stop_test
      - name: Upload Html report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: app/client-v2/playwright-report
          retention-days: 14
