name: playwright CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:

    runs-on: ubuntu-latest
    timeout-minutes: 15
        
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./app/client/package-lock.json
    - run: |
        cd ./app/client
        npm ci
        cd ../server
        npm ci
    - name: get config file
      run: cp ./src/resources/config.json.in ./src/resources/config.json
    - name: Run all components
      run: ./scripts/run_test 
    - name: Run e2e tests
      run: |
        cd ./app/client
        npx playwright test
